title: LazyInq
author: Swastika mukherjee
email: natuthakiscool@gmail.com
description: I love ashutosh Chandra !!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ashukid.github.io"
# github_username:  ashukid

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

disqus:
  shortname: https-ashukid-github-io

header_pages:
  - blogs.md
  - about.md

